chore: change Cargo.toml dependencies version
cau-overchaos/bidrum pull request #21
Opened 2024-04-28 09:29 UTC by boulce

ffmpeng-next = "6.1.1" -> "7.0.0", device_query = "1.1.3" -> "2.0.0". because before version dosen't work on rust version 1.77.2

2024-04-28 14:52 UTC, LiteHell approved these changes
LGTM

2024-04-28 16:30 UTC, LiteHell requested changes
See git commitor name and email address.

2024-04-29 02:00 UTC, boulce commented
> See git commitor name and email address.

Do you want me to change authors?
```authors = ["Yeonjin Shin <litehell@litehell.info>"]```

2024-04-29 03:35 UTC, LiteHell approved these changes
LGTM

2024-04-30 08:26 UTC, merged