Apply temporary background video for title and tutorial dialog
cau-overchaos/bidrum pull request #37
Opened 2024-05-17 16:24 UTC by LiteHell

It uses [Seoul Korea - Free Paper Style Background Loop](https://www.youtube.com/watch?v=6G_v0eLtbRE).

## Screenshots
![Title preview](https://github.com/cau-overchaos/bidrum/assets/12497886/f79ef426-b4c6-4338-9d73-32ee130fcdff)

![Tutorial dialog preview](https://github.com/cau-overchaos/bidrum/assets/12497886/533ceff9-998d-4eaf-be96-dec9601ddb14)

2024-05-18 13:43 UTC, firekann approved these changes
LGTM

2024-05-18 16:24 UTC, firekann approved these changes
LGTM

2024-05-19 01:50 UTC, boulce requested changes

2024-05-19 01:50 UTC, boulce commented on game/src/game/tutorial.rs
> +    time::{Duration, Instant},
time::Duration is not used

2024-05-19 05:03 UTC, boulce approved these changes
LGTM

2024-05-19 05:41 UTC, merged