More effects on chart player
cau-overchaos/bidrum pull request #44
Opened 2024-05-20 11:17 UTC by LiteHell

- Perodic when doing nothing
- Effect when the note is judged
- Effect for janggu icon at center when it's hitted

2024-05-20 11:36 UTC, firekann approved these changes
LGTM

2024-05-20 14:10 UTC, boulce requested changes
I don't know it is your intention, at first of the game play, the janggu icon reduces even though user press nothing.

2024-05-20 14:32 UTC, LiteHell commented on game/src/game/game_player/chart_player_ui.rs
> +        // calc janggu icon size
yes

2024-05-20 14:40 UTC, LiteHell commented on game/src/game/game_player/chart_player_ui.rs
> +                println!("drawing disappearing note at {}", i.note.distance);
Fixed on 3b8cf9584e771362e471e6177a09660920b32fbc

2024-05-20 14:40 UTC, LiteHell commented on game/src/game/game_player/chart_player_ui.rs
> +        // calc janggu icon size
Modified on 4a6d128ebffbe7c45ec574dfef8b8b1c9ac23135

2024-05-20 14:40 UTC, LiteHell commented
> I don't know it is your intention, at first of the game play, the janggu icon reduces even though user press nothing.

Fixed on 40811f38b98ff8223e1ef5117a39ac749065a5af

2024-05-20 14:50 UTC, boulce requested changes
After start game immediately, if you press just K, it doesn't react, meaning the janggu icon doesn't increase

2024-05-21 01:27 UTC, LiteHell commented
> After start game immediately, if you press just K, it doesn't react, meaning the janggu icon doesn't increase

Fixed on 15a70afce5a3c1f33c3f4fd195cc568b35fe3db7

2024-05-21 01:38 UTC, boulce approved these changes
LGTM

2024-05-21 01:49 UTC, merged