playing random combo sound
cau-overchaos/bidrum pull request #48
Opened 2024-05-22 14:54 UTC by boulce

- playing random combo sound

2024-05-22 15:23 UTC, LiteHell requested changes
- I think `chu-imsae-by-someone-1.wav`, for example, is better for audio filename.
- I think option to turn off chu-imsae in gameplay is needed... but it's not critical issue, therefore can be handled, in future, in another PR.

2024-05-22 15:23 UTC, LiteHell commented on game/src/game/game_player/effect_sound_player.rs
> +fn load_combo_sounds() -> [StaticSoundData; 10] {
I think It's better not to set volume when setting combo sounds

2024-05-22 15:23 UTC, LiteHell commented on game/src/game/game_player/effect_sound_player.rs
> +                        .play(combo_sound.clone())
Volume can set here by using `combo_sound.clone().with_settings(StaticSoundSettings::default().volume(50.0))` instead of `combo_sound.clone()`

2024-05-23 02:04 UTC, LiteHell approved these changes
LGTM

2024-05-25 16:16 UTC, firekann approved these changes
LGTM

2024-05-26 02:04 UTC, merged