Fix judgement bug of two notes at same time
cau-overchaos/bidrum pull request #9
Opened 2024-04-10 17:00 UTC by LiteHell

- Fixes a bug that only one note is judged when there're two notes at the same time
- If there're two notes judged at a time, **worst** judgement result is displayed.

2024-04-16 10:47 UTC, firekann requested changes
There is a bug where both keys do not press simultaneously.

2024-04-16 10:58 UTC, boulce approved these changes
LGTM

2024-04-19 09:11 UTC, LiteHell commented
> There is a bug where both keys do not press simultaneously.

It's not a bug caused by this PR. The bug will be fixed by PR #19.

2024-04-19 15:02 UTC, firekann approved these changes

2024-04-19 16:53 UTC, merged